### PR TITLE
fix: 64G cc sector cannot generate pieceinfo file

### PR DESCRIPTION
**Pull request by diwufeiwen**

### CODE REVIEW

**Comment by caijian76** [comment]
64G cc sector cannot generate pieceinfo file yet. No work.

**Comment by diwufeiwen** [comment]
> 64G cc sector cannot generate pieceinfo file yet. The fix No work.

This is to fix the problem that the sector was not generated when starting from the beginning, rather than the repair of the error in the previous version. Our test has passed, if you have not generated the previous version. There are two options 1. Create the file /var/tmp/s-piece-infos-68719476736 to write:
[{"Size":68719476736,"PieceCID":{"/":"baga6ea4seaqomqafu276g53zko4k23xzh4h4uecjwicbmvhsuqi7o4bhthhm4aq"}}] 2. Delete /var/tmp/s-basic-unsealed-68719476736 and create a new sector

**Comment by caijian76** [comment]
I delete s-basic-unsealed-68719476736 ,and create the s-piece-infos-68719476736 file .than pledge a new sector ,sealing job show  new sector status is AP , and work computer transfer large amounts of data from the sealer computer .took 2-3 minutes. I can see  new s-basic-unsealed-68719476736 created. every new pledge alway took 2-10 min yet.

**Comment by caijian76** [comment]
sealer must have 2 file ,and success skip AP.

**Comment by diwufeiwen** [comment]
> sealer must have 2 file ,and success skip AP.

Thank you for your enthusiasm recovery. We suggest that this kind of more complex problem is best described in a little more detail in the actual scene, so that we can quickly locate the problem. It’s better to raise a new issue for a new issue, because the merged PR is not easy to deal with again

**Pull request merged**
